//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Content.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Content.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на var MessageNumber = 1;
        ///var KeepaliveInterval = 1000 * 60 * 15;
        ///
        ///var GAME_ID = 1;
        ///var SLS_URL = &quot;http://127.0.0.1/list.en&quot;;
        ///var CURRENT_LANGUAGE = &quot;en&quot;;
        ///var CUSTOMER_SUPPORT_URL = &quot;&quot;;
        ///var GAME_EXE = &quot;Client/TL.exe&quot;;
        ///var ACCOUNT_NAME = &quot;#ACCOUNT_NAME#&quot;;
        ///var ACCOUNT_EMAIL = &quot;#ACCOUNT_EMAIL#&quot;;
        ///
        ///var LAUNCHER_EXIT_MSGS = {};
        ///
        ///LAUNCHER_EXIT_MSGS[&quot;0111&quot;] = &quot;SLS download error&quot;;
        ///LAUNCHER_EXIT_MSGS[&quot;ffff&quot;] = &quot;Fatal game client exception&quot;;
        ///LAUNCHER_EXIT_MSGS[&quot;0112&quot;] = &quot;Game string error&quot;;
        ///LAUNCHER_EXIT [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TeraLauncher_login {
            get {
                return ResourceManager.GetString("TeraLauncher_login", resourceCulture);
            }
        }
    }
}
